name: Poll for changes to start a deploy to CF

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check for CHAIN_URL
        id: check_chain_url
        run: |
          if [ -z "${{ vars.CHAIN_URL }}" ]; then
            echo "CHAIN_URL environment variable does not exist. Skipping workflow."
            echo "URL_EXISTS=false" >> $GITHUB_ENV
          else
            echo "CHAIN_URL environment variable found."
            echo "URL_EXISTS=true" >> $GITHUB_ENV
            echo "CHAIN_URL=${{ vars.CHAIN_URL }}" >> $GITHUB_ENV
          fi

      - name: Run bash command
        if: env.URL_EXISTS == 'true'
        run: |
          # Define the URL from the environment variable
          URL="${{ env.CHAIN_URL }}/agoric/vstorage/data/published.vaultFactory.governance"

          # Fetch the new value
          NEW_REFERENCED_UI=$(curl -s $URL | jq -r '.value' | jq -r '.values[]' | jq -r .body | sed 's/^#//' | jq -r .current.ReferencedUI.value)

          # Path to store the previous value
          OLD_REFERENCED_UI_FILE="./DEPLOYED_HASH"

          # Check if the previous value exists
          if [ -f "$OLD_REFERENCED_UI_FILE" ]; then
            # Read the previous value
            OLD_REFERENCED_UI=$(cat $OLD_REFERENCED_UI_FILE)
          else
            # File does not exist, set previous value to empty
            OLD_REFERENCED_UI=""
          fi

          # Output the values for the next step
          echo "NEW_VALUE=$NEW_REFERENCED_UI" >> $GITHUB_ENV
          echo "PREVIOUS_VALUE=$OLD_REFERENCED_UI" >> $GITHUB_ENV

      - name: Update DEPLOYED_HASH if value changed
        if: env.NEW_VALUE != env.PREVIOUS_VALUE && env.URL_EXISTS == 'true'
        run: |
          # Define the path to the previous value file
          REFERENCED_UI_FILE="./DEPLOYED_HASH"

          # Save the new value to the DEPLOYED_HASH file
          echo "$NEW_VALUE" > $REFERENCED_UI_FILE

          # Configure git and commit changes
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $REFERENCED_UI_FILE
          git commit -m "Update DEPLOYED_HASH with new value"
          git push
      - name: Checkout commit and push to deploy-production
        if: env.NEW_VALUE != env.PREVIOUS_VALUE && env.URL_EXISTS == 'true'
        run: |
          # Define the path to the previous value file
          REFERENCED_UI_FILE="./DEPLOYED_HASH"

          # Read the commit hash from the DEPLOYED_HASH file
          COMMIT_HASH=$(cat $REFERENCED_UI_FILE)

          # Check out the commit
          git checkout $COMMIT_HASH

          # Create or update the deploy-production branch
          git checkout -B deploy-production
          git push -f origin deploy-production
